---
- name: Install Apache2 on Ubuntu
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Ensure Apache2 is started and enabled
  service:
    name: apache2
    state: started
    enabled: yes
