---
# tasks file for mysql-role

- name: Install MySQL Server on Ubuntu
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Ensure MySQL is started and enabled
  service:
    name: mysql
    state: started
    enabled: yes
