---
- name: Install NGINX on Ubuntu
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Ensure NGINX is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes
